### ISSUE TITLE
Problema con inserimento righe sopra la tabella

### ISSUE THREAD

**Issue by albertoforcato** [4skinSkywalker/OM-generator#1]
Quando vengono inserite delle righe sopra la tabella contenente i dati e non vengono popolate, excel non salva in modo logico l'ordine delle righe.

**Comment by 4skinSkywalker** [comment]
Grazie Alberto, provvederò alla risoluzione della falla ASAP.

**Comment by 4skinSkywalker** [comment]
La issue è stata risolta con il commit **0ba3bead58f20feed5f798e8f6ec33450e0fce1f**.
Grazie!
